<a href="https://colab.research.google.com/github/naufalnashif/data-engineer-test-case/blob/main/DE_cybertrend_datamart.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Import Dependencies

In [1]:
import pandas as pd
from datetime import datetime

# Load Data SD Coklat, SD Jingga, SD Ungu

In [2]:
data_sdCoklat = pd.read_csv("/content/SD_Coklat-transform_Ready.csv")
data_sdJingga = pd.read_csv("/content/SD_jingga-transform_Ready.csv")
data_sdUngu = pd.read_csv("/content/SD_ungu-transform_Ready.csv")

In [3]:
data_sdCoklat

,NIS,school,fullName,gender,grade,POB,birth,age,caturWulan,subjects,midTest,finalTest,mean,finalScore
0,Std001,SD Coklat,Ika Tiara Alatas,F,6,Pariaman,2011-01-05,13,1,Math,95,82,88.5,A
1,Std001,SD Coklat,Ika Tiara Alatas,F,6,Pariaman,2011-01-05,13,2,Math,66,76,71.0,B
2,Std001,SD Coklat,Ika Tiara Alatas,F,6,Pariaman,2011-01-05,13,3,Math,59,84,71.5,B
3,Std001,SD Coklat,Ika Tiara Alatas,F,6,Pariaman,2011-01-05,13,1,Science,71,75,73.0,B
4,Std001,SD Coklat,Ika Tiara Alatas,F,6,Pariaman,2011-01-05,13,2,Science,77,90,83.5,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5395,Std300,SD Coklat,Camilla Gadis Rajagukguk,F,1,Tangerang Selatan,2016-06-06,7,2,English,51,78,64.5,C
5396,Std300,SD Coklat,Camilla Gadis Rajagukguk,F,1,Tangerang Selatan,2016-06-06,7,3,English,57,98,77.5,B
5397,Std300,SD Coklat,Camilla Gadis Rajagukguk,F,1,Tangerang Selatan,2016-06-06,7,1,Religion,61,85,73.0,B
5398,Std300,SD Coklat,Camilla Gadis Rajagukguk,F,1,Tangerang Selatan,2016-06-06,7,2,Religion,70,88,79.0,B
5399,Std300,SD Coklat,Camilla Gadis Rajagukguk,F,1,Tangerang Selatan,2016-06-06,7,3,Religion,89,64,76.5,B

In [4]:
data_sdJingga

,NIS,school,fullName,gender,grade,POB,birth,age,caturWulan,subjects,midTest,finalTest,mean,finalScore
0,Std001,SD Jingga,Julie Helena Saad,F,6,Subulussalam,2011-04-02,12,1,Math,91,74,82.5,B
1,Std001,SD Jingga,Julie Helena Saad,F,6,Subulussalam,2011-04-02,12,2,Math,98,68,83.0,B
2,Std001,SD Jingga,Julie Helena Saad,F,6,Subulussalam,2011-04-02,12,3,Math,96,68,82.0,B
3,Std001,SD Jingga,Julie Helena Saad,F,6,Subulussalam,2011-04-02,12,1,Science,61,84,72.5,B
4,Std001,SD Jingga,Julie Helena Saad,F,6,Subulussalam,2011-04-02,12,2,Science,76,53,64.5,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5395,Std300,SD Jingga,Amien Baim Manopo,M,1,Bengkulu,2018-03-05,5,2,English,95,77,86.0,A
5396,Std300,SD Jingga,Amien Baim Manopo,M,1,Bengkulu,2018-03-05,5,3,English,50,73,61.5,C
5397,Std300,SD Jingga,Amien Baim Manopo,M,1,Bengkulu,2018-03-05,5,1,Religion,82,63,72.5,B
5398,Std300,SD Jingga,Amien Baim Manopo,M,1,Bengkulu,2018-03-05,5,2,Religion,57,58,57.5,C
5399,Std300,SD Jingga,Amien Baim Manopo,M,1,Bengkulu,2018-03-05,5,3,Religion,60,80,70.0,B

In [5]:
data_sdUngu

,NIS,school,fullName,gender,grade,POB,birth,age,caturWulan,subjects,midTest,finalTest,mean,finalScore
0,Std001,SD Ungu,Mirza Patria Budiman,M,6,Tangerang,2009-09-18,14,1,Math,90,67,78.5,B
1,Std001,SD Ungu,Mirza Patria Budiman,M,6,Tangerang,2009-09-18,14,2,Math,51,97,74.0,B
2,Std001,SD Ungu,Mirza Patria Budiman,M,6,Tangerang,2009-09-18,14,3,Math,99,61,80.0,B
3,Std001,SD Ungu,Mirza Patria Budiman,M,6,Tangerang,2009-09-18,14,1,Science,78,78,78.0,B
4,Std001,SD Ungu,Mirza Patria Budiman,M,6,Tangerang,2009-09-18,14,2,Science,70,62,66.0,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5395,Std300,SD Ungu,Kemala Agusta Taslim,F,1,Langsa,2014-07-23,9,2,English,56,83,69.5,B
5396,Std300,SD Ungu,Kemala Agusta Taslim,F,1,Langsa,2014-07-23,9,3,English,60,62,61.0,C
5397,Std300,SD Ungu,Kemala Agusta Taslim,F,1,Langsa,2014-07-23,9,1,Religion,87,76,81.5,B
5398,Std300,SD Ungu,Kemala Agusta Taslim,F,1,Langsa,2014-07-23,9,2,Religion,67,61,64.0,C
5399,Std300,SD Ungu,Kemala Agusta Taslim,F,1,Langsa,2014-07-23,9,3,Religion,100,76,88.0,A

## Concat dataframe

In [19]:
# Gabungkan DataFrame menggunakan pd.concat
dataMart = pd.concat([data_sdCoklat, data_sdJingga, data_sdUngu], ignore_index=True)
dataMart

,NIS,school,fullName,gender,grade,POB,birth,age,caturWulan,subjects,midTest,finalTest,mean,finalScore
0,Std001,SD Coklat,Ika Tiara Alatas,F,6,Pariaman,2011-01-05,13,1,Math,95,82,88.5,A
1,Std001,SD Coklat,Ika Tiara Alatas,F,6,Pariaman,2011-01-05,13,2,Math,66,76,71.0,B
2,Std001,SD Coklat,Ika Tiara Alatas,F,6,Pariaman,2011-01-05,13,3,Math,59,84,71.5,B
3,Std001,SD Coklat,Ika Tiara Alatas,F,6,Pariaman,2011-01-05,13,1,Science,71,75,73.0,B
4,Std001,SD Coklat,Ika Tiara Alatas,F,6,Pariaman,2011-01-05,13,2,Science,77,90,83.5,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16195,Std300,SD Ungu,Kemala Agusta Taslim,F,1,Langsa,2014-07-23,9,2,English,56,83,69.5,B
16196,Std300,SD Ungu,Kemala Agusta Taslim,F,1,Langsa,2014-07-23,9,3,English,60,62,61.0,C
16197,Std300,SD Ungu,Kemala Agusta Taslim,F,1,Langsa,2014-07-23,9,1,Religion,87,76,81.5,B
16198,Std300,SD Ungu,Kemala Agusta Taslim,F,1,Langsa,2014-07-23,9,2,Religion,67,61,64.0,C
16199,Std300,SD Ungu,Kemala Agusta Taslim,F,1,Langsa,2014-07-23,9,3,Religion,100,76,88.0,A

## Buat Email

In [23]:
# Fungsi untuk membuat email
def create_email(row):
    first_name_initial = row['fullName'].split()[0][0].lower()
    last_name = row['fullName'].split()[-1].lower()
    email = f"{first_name_initial}.{last_name}@sekolah.edu.id"
    return email

dataMart['email'] = dataMart.apply(create_email, axis=1)


# duplicate_emails = dataMart[dataMart.duplicated(subset='email', keep=False)]['email']
# print("Emails with Duplicates:")
# print(duplicate_emails)

# # Menambahkan sufix unik jika ada duplikasi
# dataMart['email'] = dataMart.groupby('email').cumcount().astype(str).replace('0', '') + '_' + dataMart['email'].astype(str)

## Buat kolom ID

In [24]:
dataMart['ID'] = range(1, len(dataMart) + 1)

## Standarisasi NIS

In [25]:
dataMart['Std-NIS'] = dataMart['NIS'] + '-' + dataMart['school'].str.split().str[1]
dataMart

,NIS,school,fullName,gender,grade,POB,birth,age,caturWulan,subjects,midTest,finalTest,mean,finalScore,ID,Std-NIS,email
0,Std001,SD Coklat,Ika Tiara Alatas,F,6,Pariaman,2011-01-05,13,1,Math,95,82,88.5,A,1,Std001-Coklat,i.alatas@sekolah.edu.id
1,Std001,SD Coklat,Ika Tiara Alatas,F,6,Pariaman,2011-01-05,13,2,Math,66,76,71.0,B,2,Std001-Coklat,i.alatas@sekolah.edu.id
2,Std001,SD Coklat,Ika Tiara Alatas,F,6,Pariaman,2011-01-05,13,3,Math,59,84,71.5,B,3,Std001-Coklat,i.alatas@sekolah.edu.id
3,Std001,SD Coklat,Ika Tiara Alatas,F,6,Pariaman,2011-01-05,13,1,Science,71,75,73.0,B,4,Std001-Coklat,i.alatas@sekolah.edu.id
4,Std001,SD Coklat,Ika Tiara Alatas,F,6,Pariaman,2011-01-05,13,2,Science,77,90,83.5,B,5,Std001-Coklat,i.alatas@sekolah.edu.id
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16195,Std300,SD Ungu,Kemala Agusta Taslim,F,1,Langsa,2014-07-23,9,2,English,56,83,69.5,B,16196,Std300-Ungu,k.taslim@sekolah.edu.id
16196,Std300,SD Ungu,Kemala Agusta Taslim,F,1,Langsa,2014-07-23,9,3,English,60,62,61.0,C,16197,Std300-Ungu,k.taslim@sekolah.edu.id
16197,Std300,SD Ungu,Kemala Agusta Taslim,F,1,Langsa,2014-07-23,9,1,Religion,87,76,81.5,B,16198,Std300-Ungu,k.taslim@sekolah.edu.id
16198,Std300,SD Ungu,Kemala Agusta Taslim,F,1,Langsa,2014-07-23,9,2,Religion,67,61,64.0,C,16199,Std300-Ungu,k.taslim@sekolah.edu.id
16199,Std300,SD Ungu,Kemala Agusta Taslim,F,1,Langsa,2014-07-23,9,3,Religion,100,76,88.0,A,16200,Std300-Ungu,k.taslim@sekolah.edu.id

## Reorder columns

In [26]:
dataMart = dataMart[['ID','Std-NIS', 'NIS', 'school', 'fullName','email', 'gender', 'grade', 'POB', 'birth', 'age', 'caturWulan', 'subjects', 'midTest', 'finalTest', 'mean', 'finalScore']]
dataMart

,ID,Std-NIS,NIS,school,fullName,email,gender,grade,POB,birth,age,caturWulan,subjects,midTest,finalTest,mean,finalScore
0,1,Std001-Coklat,Std001,SD Coklat,Ika Tiara Alatas,i.alatas@sekolah.edu.id,F,6,Pariaman,2011-01-05,13,1,Math,95,82,88.5,A
1,2,Std001-Coklat,Std001,SD Coklat,Ika Tiara Alatas,i.alatas@sekolah.edu.id,F,6,Pariaman,2011-01-05,13,2,Math,66,76,71.0,B
2,3,Std001-Coklat,Std001,SD Coklat,Ika Tiara Alatas,i.alatas@sekolah.edu.id,F,6,Pariaman,2011-01-05,13,3,Math,59,84,71.5,B
3,4,Std001-Coklat,Std001,SD Coklat,Ika Tiara Alatas,i.alatas@sekolah.edu.id,F,6,Pariaman,2011-01-05,13,1,Science,71,75,73.0,B
4,5,Std001-Coklat,Std001,SD Coklat,Ika Tiara Alatas,i.alatas@sekolah.edu.id,F,6,Pariaman,2011-01-05,13,2,Science,77,90,83.5,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16195,16196,Std300-Ungu,Std300,SD Ungu,Kemala Agusta Taslim,k.taslim@sekolah.edu.id,F,1,Langsa,2014-07-23,9,2,English,56,83,69.5,B
16196,16197,Std300-Ungu,Std300,SD Ungu,Kemala Agusta Taslim,k.taslim@sekolah.edu.id,F,1,Langsa,2014-07-23,9,3,English,60,62,61.0,C
16197,16198,Std300-Ungu,Std300,SD Ungu,Kemala Agusta Taslim,k.taslim@sekolah.edu.id,F,1,Langsa,2014-07-23,9,1,Religion,87,76,81.5,B
16198,16199,Std300-Ungu,Std300,SD Ungu,Kemala Agusta Taslim,k.taslim@sekolah.edu.id,F,1,Langsa,2014-07-23,9,2,Religion,67,61,64.0,C
16199,16200,Std300-Ungu,Std300,SD Ungu,Kemala Agusta Taslim,k.taslim@sekolah.edu.id,F,1,Langsa,2014-07-23,9,3,Religion,100,76,88.0,A

In [27]:
dataMart.to_csv("dataMart.csv", index=False)
dataMart.to_excel("dataMart.xlsx", index=False)